name: Build and Test BaccaratGameService

on:
  push:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t telecasino-baccarat .

      - name: Run container in background
        run: |
          docker run -d --name baccarat -p 8080:8080 telecasino-baccarat
          sleep 10  # wait for the API to start

      - name: Test API endpoint
        run: |
          curl -v -X POST \
            'http://localhost:8080/api/Baccarat/play?wager=1&bet=tie&gameSessionId=23' \
            -H 'accept: text/plain' \
            -H 'Content-Type: application/json'

      - name: Test video availability
        run: |
          ID=$(curl -s -X POST \
            'http://localhost:8080/api/Baccarat/play?wager=1&bet=tie&gameSessionId=23' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' | jq -r '.id') && \
          curl -s -o /dev/null -w "%{http_code}\n" "http://localhost:8080/${ID}.mp4"

      - name: Show folder tree
        run: |
          docker exec baccarat tree /shared/Baccarat

      - name: Stop container
        if: always()
        run: docker stop baccarat
